### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by rozbb** [gsingh93/trace#3]
using a global `static mut depth` isn't thread safe. It's possible to just replace the global with a thread-local like `thread_local!(static STATIC_DEPTH: RefCell<usize> = RefCell::new(0))` but it still has to be entered by the user and it's long.

**Comment by hcpl** [comment]
Your suggestion is implemented in https://github.com/gsingh93/trace/pull/22 (specifically, the https://github.com/gsingh93/trace/pull/22/commits/352a48fe3106defa3237e5ac454814840c3bbaa6 commit).

I used `Cell<usize>` instead of `RefCell<usize>` though, since `usize` is a `Copy` type and `Cell` has less overhead.
